name: Versionup Patch

on:
  workflow_dispatch:

jobs:
  versionup-patch:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn --frozen-lockfile
      - name: git config
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: create release
        run: |
          git fetch --tags
          git checkout -b release_today
          git push --set-upstream origin release_today
      - name: version up
        run: |
          yarn versionup:patch --yes
          git push
      # - name: set git tag
      #   run: |
      #     echo "tag_no=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      # - name: Create release PR
      #   uses: peter-evans/create-pull-request@v3
      #   with:
      #     branch: release_today
      #     base: main
      #     title: Deploy ${{ env.tag_no }}
      #     draft: false


