name: Versionup Patch

on:
  workflow_dispatch:

env:
  RELEASE_BRANCH: release

jobs:
  versionup-patch:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'refs/heads/main'
          fetch-depth: 0 # All history
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn --frozen-lockfile
      - name: git config
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: create release
        run: |
          git fetch --tags
          git checkout -b release
          git push --set-upstream origin release
      - name: version up
        run: |
          yarn versionup:patch --yes
          echo "hoge" >> '.gitignore'
          git add .
          git commit -nm "hoge"
          git push
      - name: set git tag
        run: |
          echo "tag_no=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: Create release PR
        id: create_release_pr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: release
          base: main
          title: Deploy ${{ env.tag_no }}
          draft: false


