name: Versionup Patch

on:
  workflow_dispatch:

env:
  RELEASE_BRANCH: release_today

jobs:
  versionup-patch:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn --frozen-lockfile
      - name: git config
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: create release
        run: |
          git fetch --tags
          git checkout -b ${{ env.RELEASE_BRANCH }}
          git push --set-upstream origin ${{ env.RELEASE_BRANCH }}
      - name: version up
        run: |
          yarn versionup:patch --yes
      - name: set git tag
        run: |
          echo "tag_no=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: Deploy ${{ env.tag_no }}
        run: |
          hub pull-request -m "${{ env.MESSAGE }}" -b main -h ${{ env.RELEASE_BRANCH }}


