name: Versionup Patch

on:
  workflow_dispatch:

jobs:
  versionup-patch:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn --frozen-lockfile
      - name: git config
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: create release
        run: |
          git fetch --tags
          git checkout -b release
          git push --set-upstream origin release
      - name: version up
        run: |
          yarn versionup:patch --yes
          git push
      - name: set git tag
        run: |
          echo "tag_no=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      # - name: Create Pull Request
      #   id: create_pull_request
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     BRANCH_NAME: release
      #     MESSAGE: deploy ${{ env.tag_no }}
      #   run: |
      #     PULL_REQUEST_MESSAGE=`echo -e "$MESSAGE"`
      #     hub pull-request -m "${{ env.MESSAGE }}" -b main -h release
      - name: Create release PR
        uses: peter-evans/create-pull-request@v4
        with:
          branch: release
          base: main
          title: Deploy ${{ env.tag_no }}
          draft: false


